name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          config_timezone: Asia/Shanghai
          config_display: large
          repositories_skipped: |
            vdriasworld/whitelist-dashboard
            vdriasworld/manual
            vdriasworld/Region_BackUp
          
          plugin_notable: yes
          plugin_notable_indepth: yes
          plugin_notable_repositories: yes
          plugin_notable_from: all
          plugin_notable_types: commit, issue, pull_request
          
          plugin_languages: yes
          plugin_languages_indepth: yes
          plugin_languages_ignored: >-
            html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell,
            gnuplot, javascript, ejs, stylus
          plugin_languages_sections: most-used
          plugin_languages_colors: csharp:#3b831b, c++:#e35c7e
