name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          config_display: large
          plugin_notable: yes
          plugin_notable_skipped: |
            vdriasworld/whitelist-dashboard
            vdriasworld/manual
            vdriasworld/Region_BackUp
